### ISSUE TITLE
No Cave entry

### ISSUE THREAD

**Issue by Thebegginer1** [Quidvio/No-Caves-World-Generation#2]
In Retro caves most of the caves end below the surface.
ALready tried something like: "type": "minecraft:worldgen/biome",
    "generator": {
        "type": "minecraft:cave",
        "probability": 0.4
    }      but it did not work.

**Comment by klinbee** [comment]
![image](https://github.com/Quidvio/No-Caves-World-Generation/assets/105707614/92b35a5a-f053-4032-9b1f-1c23026534de)
Adding this image for context for anyone who views this on GH only.

I've altered the cave probability, distribution, and size to account for the changes between 1.17 and 1.18. 

I've realized that a lot that was missing was not only the fact that the probability of generating and generation range changed, but also the average distance between caves as well (since their size is different compared to the size of the world now)

I've done a lot of tweaking to make sure they are more common on the surface, and not just more common on the surface in low-land areas. So if you find a higher elevation area, you should still see caves frequently as well. Additionally, I've lowered the ranges of these so that lava ravines can make a come back! (These previously didn't generate in 1.18+).

Finally, I've messed with settings to make water caves less expansive and less common. Separation between water and cave areas should be less awkward too (often water would just flow into caves if they were close to each other).

I would've removed them completely if 1. that were possible 2. that would not totally ruin rivers/oceans.
